networks:
  transcendence:
    driver: bridge

services:
  frontend:
    build:
      context: ../
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    env_file:
      - ../.env
    restart: always
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/frontend/node_modules
    networks:
      - transcendence
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    env_file:
      - ../.env
    restart: always
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/backend/node_modules
      - uploads_data:/app/backend/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence
  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8443:443"
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - uploads_data:/usr/share/nginx/uploads:ro
    networks:
      - transcendence
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence
volumes:
  postgres_data:
  uploads_data:
