name: ft_transcendence_prod

networks:
  transcendence:
    driver: bridge

services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend/Dockerfile.prod
    container_name: backend
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - uploads_data:/app/backend/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile.prod
    container_name: nginx
    restart: always
    ports:
      - "8443:8443"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - uploads_data:/usr/share/nginx/uploads:ro
    networks:
      - transcendence
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence
volumes:
  postgres_data:
  uploads_data:
