// frontend のみで使う定数を定義

export const SCENE_CONFIG = {
  grid: {
    centerDivisor: 2,
    y: -0.48,
  },
  camera: {
    height: 8,
    distanceFromCenter: 7,
    fov: 58,
  },
  light: {
    ambientIntensity: 0.42,
    directionalPosition: [10, 10, 5] as [number, number, number],
    directionalIntensity: 0.7,
    pointHeight: 3,
    pointIntensity: 4,
    pointDistance: 15,
  },
  orbit: {
    minDistance: 6,
    maxDistance: 14,
    maxPolarAngleRatio: 0.46,
  },
  ground: {
    y: -0.5,
    sizePadding: 1,
    reflectorBlur: [300, 80] as [number, number],
    reflectorResolution: 512,
    reflectorMixBlur: 1,
    reflectorMixStrength: 40,
    reflectorRoughness: 0.22,
    reflectorDepthScale: 1,
    minDepthThreshold: 0.4,
    maxDepthThreshold: 1.2,
  },
  blocks: {
    solidSize: [1, 1, 1] as [number, number, number],
    solidPillarSize: [0.5, 1.1, 0.5] as [number, number, number],
    breakableCoreRadius: 0.35,
    breakableCoreSegments: 16,
    breakableShellSize: [0.9, 0.9, 0.9] as [number, number, number],
    breakableShellOpacity: 0.6,
    metallicMetalness: 0.9,
    solidEdgeOpacity: 0.22,
    breakableEmissiveIntensity: 2,
  },
  bombs: {
    coreRadius: 0.3,
    coreSegments: 32,
    auraRadius: 0.4,
    auraSegments: 16,
    emissiveIntensity: 4,
    auraOpacity: 0.4,
  },
  colors: {
    background: '#010103',
    ground: '#050510',
    gridCell: '#222222',
    gridSection: '#00ffff',
    solidBlock: '#080808',
    solidPillar: '#111111',
    solidEdge: '#00ffff',
    breakableShell: '#111111',
    breakableEdge: '#333333',
    localBomb: '#ffffff',
    localBombEmissive: '#00ffff',
    enemyBomb: '#ff0000',
    enemyBombEmissive: '#ff0000',
    bombAura: '#ffffff',
    pointLight: '#ff00ff',
  },
  playerLabel: {
    height: 0.95,
    zIndexRange: [9, 0] as [number, number], // usernameのオーバーレイを3Dより手前に、結果画面より奥に表示するため
  },
}
